linea-it/dri

api/oacc.py

- Added function - get_columns_table, which returns table columns, column type, and the comment for the table on NCSA (though few tables have comments)
- Rewrite function fetch_columns, which returns only the table columns, also used for other functions

close Issue92

---

api/product_classifier/fixtures/initial_data.json
api/product_classifier/models.py

and changed the initial data by setting some of the groups.

Closed #98 - add 'is_catalog' field to model product Group

---

api/coadd/datadiscovery.py
api/coadd/management/commands/datadiscovery.py
api/dri/settings/local_vars.py.template
datadiscovery.sh

Registry y3a2

---

.gitignore

commit message: BODY on PULL REQUEST: task tal history tal

commit message: TITLE on PULL REQUEST: task tal history tal

---

.gitignore

THIS IS THE COMMENT OF MY PULL REQUEST

commit message: THIS IS THE COMMIT MESSAGE OF MY PULL REQUEST

---

api/common/views.py
api/dri/settings/defaults.py
api/dri/urls.py
api/requirements.txt
api/templates/account/login.html
api/templates/rest_framework/login.html

Making social login buttons activated by configuration.
Now the social login buttons will only show if they are configured on admin.
**Requires server restart to show or hide the buttons

Login - Usuário Autenticado (Ajustes - FACEBOOK)

---

api/lib/CatalogDB.py

A solução foi corrigir a função parse_url_filters
adicionando a correção de cos e pi a conversão de lon, lat.

Closed #1080 - Fix query by square using radius

---

api/coadd/views.py
frontend/eyeballing/src/components/DatasetList.js
frontend/eyeballing/src/components/SearchField.js
frontend/eyeballing/src/home.js

It was added to the eyeballing tile inspection page the input search function

Adding of search input function

---

frontend/eyeballing/src/components/DatasetList.js
frontend/eyeballing/src/components/SearchField.js
frontend/eyeballing/src/components/SnackBar.js
frontend/eyeballing/src/home.js

It was created a message box that shows "saved succesfully" every tile qualified by the user.

Adding of a message box when user qualify the tile

---

frontend/eyeballing/src/components/SearchField.js
frontend/eyeballing/src/home.js
frontend/eyeballing/src/theme/MaterialTheme.js

A loading indicator has been added above the list of datasets. this indicator is active every time the request is being processed.
also changed the search function that was initially remote causing a new request, now the search is being done locally.

Improve feedback

---

api/product_register/ImportProcess.py

Foi alterado o  programa de importação de produtos, para permitir um produto do tipo mapa que tenha uma imagem Aladin mas que não tem tabela exportada. 
isto é uma solução provisória o correto seria ter um tipo de produto especifico para arquivo.

Changed Import Product maps, to enable import aladin maps without table

---

Docs/Dockerfile_Sencha
docker-compose-production.yml
frontend/explorer/app/view/system/SystemController.js
frontend/nginx-proxy-develop.conf
frontend/packages/local/visiomatic/src/Visiomatic.js

As aplicações Sky, Target e Explorer agora tem o ambiente de desenvolvimento usando container. 
Ainda falta alguns ajustes como o build por exemplo.

Dev ext container

---

frontend/eyeballing/src/home.js

Fixing the focus reset when opening up the tile's comment box

---

Instalation.md

Minor improvements to the development environment installation documentation

Improved installation documentation

---

api/product/descutoutservice.py
frontend/target/app/view/settings/CutoutJobForm.js
frontend/target/app/view/settings/CutoutJobModel.js

Minor correction in the cutout, implemented make_fits = false parameter to prevent downloading unsolicited fit images.

Minor fix in cutout

---

api/product/views.py
frontend/packages/local/common/src/header/Toolbar.js
frontend/target/app/store/CatalogsTree.js
frontend/target/app/view/catalog/Tree.js
frontend/target/app/view/objects/Panel.js
frontend/target/app/view/preview/Preview.js
frontend/target/app/view/preview/PreviewController.js

- The list of target viewer catalogs is now ordered by the most recent date by default.
- The toolbar of the list of objects in the target viewer has been reorganized, now the buttons follow the natural order of execution.
- The Contact Us entry in the application menu has been removed.

Target Viwer UI improvements

---

api/catalog/serializers.py
api/catalog/views.py
frontend/packages/local/common/src/model/CommentObject.js
frontend/packages/local/visiomatic/src/Visiomatic.js
frontend/target/app/view/preview/Preview.js
frontend/target/app/view/preview/PreviewController.js
frontend/target/app/view/settings/CutoutJobForm.js

- The comment function by position has been disabled.
- Another color option was included in the cutout. 
- A bug was fixed in the Target preview that prevented the creation of a new comment.

Fixed error in target comments and other minor fixes.

---

api/product/views.py
frontend/userquery/app/view/main/Main.js
frontend/userquery/app/view/main/MainController.js

The part of the menu that listed the External Catalogs tables was removed from the user query code. 
for the image viewer, only the registration of the tables was removed.

Removed External Catalogs

---

frontend/sky/app/view/home/Home.js
frontend/target/app/view/catalog/Tree.js
frontend/target/app/view/objects/ObjectsController.js
frontend/target/app/view/settings/CutoutJobForm.js

Changed the color options for the cutouts, and fixed a bug that prevented the exchange between images.

Changed the color options for the cutouts

---

api/coadd/views.py
frontend/eyeballing/src/components/download/index.js
frontend/eyeballing/src/components/download/styles.js
frontend/eyeballing/src/home.js

The DESaccess API returns different results in the Public and Collaboration instances. A refactoring was needed to assure the data and to present it.

Fixing Tile Viewer download: separating results (colab and public)

---

api/product/views.py
frontend/nginx-proxy-develop.conf
frontend/nginx-proxy.conf
frontend/target/app/view/catalog/CSVController.js
frontend/target/app/view/catalog/CSVForm.js
frontend/target/app/view/catalog/CatalogController.js
frontend/target/app/view/catalog/RegisterWindow.js
frontend/target/app/view/catalog/Tree.js

A csv file upload system was implemented in the target viewer, it is now possible to create a new list from a csv file.
- it is possible to upload any csv file in the most common formats.
- Maximum upload size is 50Mb.
- The file can be compressed .zip or .tar.gz
- You can only have one CSV file at a time. (If the compressed file contains more than one, an error message will be displayed.)
- The operation has a time limit of 3 minutes.
- The file can have N columns as long as it has a header.
- There are no line limits, the limit is determined by the file size.
For developers:
It is necessary to configure the upload limit in Ngnix. in the server key add the parameter client_max_body_size.
```
server {
...
client_max_body_size 100M;
...    
```

Target Viewer Upload CSV file

---

api/coadd/views.py

The DESaccess changed. Now the Y6A2 is available, so there's no need to map the Y6A2 to the Y6A1. Also included some other files that appeared.

Change params DESaccess

---

api/userquery/views.py

The part that checks whether the query is valid has been altered, 
while checking the query has a fixed limit of 5 lines. #1292

Fix Userquery Connection Failure

---

api/product/descutoutservice.py

Fixed #1317 The function that registers images has been fixed, now there is a treatment to register images even if Bulk create is not supported.

Fixed Cutout register images

---

frontend/explorer/app/store/Objects.js
frontend/explorer/app/view/coadd/CoaddController.js

Changed endpoint used in Explorer to not depend on rating and reject tables. #1321

Explorer Coadd + Postgresql

---

api/activity_statistic/reports.py
api/activity_statistic/serializers.py
api/activity_statistic/templates/unique_hits_on_day.html
api/common/views.py

the bug was caused by incomplete data due to authentication tests via shibboleth

Fixed bug in sending daily emails in the LineA environment

---

api/common/views.py
api/product/descutoutservice.py

Foi adicionado uma verificação no cutout que retira da lista de posições, as posições que não estão dentro de alguma tile. 
aparentemente isso resolve os errors intermitentes no lado do DESaccess. 
nos testes apos a mudança não houve nenhuma ocorrência do erro.

Closed #1375 Added a check to not send positions outside the footprint

---

frontend/landing_page/package.json
frontend/landing_page/src/Routes/index.js
frontend/landing_page/src/Services/api.js
frontend/landing_page/src/components/Banner/index.js
frontend/landing_page/src/components/Header/index.js
frontend/landing_page/src/pages/Contact/index.js
frontend/landing_page/src/pages/Home/partials/Supporters/index.js
frontend/landing_page/src/pages/OracleEasyAccess/index.js

Added Enviroment name in landing page Banner.
And Enabled Eslint for landing_page app
Closed #1411

Added Enviroment name in landing page Banner.

---

README.md
frontend/target/app/view/objects/Panel.js

Os botões Cutout e Mosaic foram temporariamente ocultados na barra de ações do Target Viewer. 
Nenhuma função foi removida ou alterada, apenas os botões foram desabilitados e ocultados. 
No futuro quando o serviço de Cutouts do LIneA for implementado, será necessário implementar uma nova integração para o serviço de cutout. ou apenas transferir essa funcionalidade para o novo Target Viewer.

Closed #1449 - Access to functions related to cutout has been disabled.

---

frontend/target/app/view/objects/FiltersController.js
frontend/target/app/view/objects/FiltersWindow.js
frontend/target/app/view/objects/Grid.js
frontend/target/app/view/preview/Preview.js

The Classification, Rejection and comments functions in the target list have been disabled

Closed #1486 - Disabled Classification, Rejection and comments 

---

frontend/landing_page/src/pages/Contact/index.js
frontend/landing_page/src/pages/Contact/styles.js

The contact page has been redesigned for the version we are using in other LIneA projects on a provisional basis until the reCAPTCHA issue is resolved.

Closes #1463 - Task completed

---

frontend/landing_page/src/components/Footer/index.js

Fixes #1495 - The URL has been changed to the correct one

---

frontend/landing_page/src/Routes/index.js
frontend/landing_page/src/components/Header/index.js

Fixes #1464 - Now, when you click on the 'sign up' button you will be directed to the website-linea registration page

Sign up button leading to the registration page.

---

api/templates/rest_framework/login.html
frontend/landing_page/src/components/Banner/index.js

- Home Page - Title 'DES' has been changed to 'LineA'
- Login screen - The standard EDS screen has been implemented

Implemented EDS login screen and fixed title to LineA instead of DES

---

api/templates/rest_framework/login.html

Eng or Pt-Br has been replaced by English or Portuguese

---

frontend/landing_page/src/pages/Contact/index.js
frontend/landing_page/src/pages/Contact/styles.js

Improved the display of the helpdesk email and fixed the contact card margin

Email helpdesk on contact page

---

frontend/landing_page/src/pages/AboutUs/index.js

There were words stuck together (without spaces) in three different spots, which was adjusted in this pull request.

Fix: words stuck together
